### ISSUE TITLE
Populate additional GTFS feeds

### ISSUE THREAD

**Issue by ivyrze** [jmcbroom/multi-gtfs-gatsby#21]
Here are the static links for the GTFS data:

- D2A2: http://data.trilliumtransit.com/gtfs/indiantrails-mi-us/indiantrails-mi-us.zip
    - The feed includes all Indian Trails routes in Michigan, so we'll need to work out a method to reduce the data down
- Michigan Flyer: http://data.trilliumtransit.com/gtfs/michiganflyer-mi-us/michiganflyer-mi-us.zip
    - Not currently listed in the demo but something I would like to see added. Potential uses are to take SMART routes 125, 261, or 280 to DTW, transfer to the Flyer, and ride to Brighton, Ann Arbor, or East Lansing
- QLine: http://data.trilliumtransit.com/gtfs/qline-mi-us/qline-mi-us.zip
- People Mover: https://www.detroitmi.gov/Portals/0/docs/deptoftransportation/pdfs/PeopleMoverGTFS.zip
    - From my limited knowledge, it seems they may resume service here shortly. Something to keep an eye on

**Comment by jmcbroom** [comment]
Thanks, I'll pull these into the DB (People Mover excepted -- that GTFS file was created by our team and is now out of date since we built it in a Clockwise era). 

Not quite sure how we'll solve filtering yet.. but the first step will be having the data available in the database. At some point, we will need a better way to identify which feeds in the database are the ones we want to publish (right now they are stacking up over time), so perhaps we can revisit this question then. It may be something else we can build in to a custom CMS that I have suggested exploring in #22.

**Comment by jmcbroom** [comment]
This should be something we can tackle with the custom CMS.

We now have a customizable [agency object](https://github.com/jmcbroom/multi-gtfs-gatsby/blob/main/studio/schemas/agency.js) to which we can add an attribute which would denote routes to either deny/allow from being posted.

Alternately, we can create a new instance of the [route object](https://github.com/jmcbroom/multi-gtfs-gatsby/blob/main/studio/schemas/route.js) for all routes in the Indian Trails data (I wrote a Python script to do this but it should probably be a JS thing/callable by npm), and then "unpublish" the documents representing routes which we do not want to include on the site yet -- only published documents will be built by the site generator.

**Comment by jmcbroom** [comment]
Tried to ingest Michigan Flyer last night and it was kind of messed up -- didn't seem like there were any `stop_time`s associated with each trip? Need to look into this further, that feed is in the database with `feed_index = 16`

**Comment by ivyrze** [comment]
Not sure if you've since made progress on this but just a quick, manual query returned 162 `stop_times` on my end

```sql
SELECT *
FROM gtfs.trips
INNER JOIN gtfs.stop_times
ON gtfs.trips.trip_id=gtfs.stop_times.trip_id
WHERE gtfs.trips.feed_index=16
ORDER BY trips.trip_id,stop_sequence
```

In any case, Michigan Flyer is easily the least important of the agencies so I can sympathize with dropping it if it becomes overly problematic
